#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr  4 17:14:50 2024

@author: jamesdowning
"""

# Given a list of numbers and a number k, return whether any two numbers from the list add up to k. 
# For example, given [10, 15, 3, 7] and k of 17, return true since 10 + 7 is 17. 
# Bonus can you do this in one pass? 

list = [10, 15, 3, 7]

k = 17

if list[0] + list[1] == k or list[0] + list[2] == k or list[0] + list[3] == k:
    print("true")
elif list[1] + list[2] == k or list[1] + list[3] == k:
    print ("true")
elif list[2] + list[3] == k:
    print ("true")
else:
   print ("false")
